### ISSUE TITLE
NPM Install with Errors

### ISSUE THREAD

**Issue by chunggabriel** [willhlaw/node-firestore-backup-restore#2]
Hi,
It has error message when the firestore-bakcup-restore was installed.
What can we do?
Thanks
gab
[npm-debug.log](https://github.com/willhlaw/node-firestore-backup-restore/files/1566749/npm-debug.log)

**Comment by rajapattanayak** [comment]
Not able to install through npm. git repo url in redme file seems incorrect.

**Comment by chunggabriel** [comment]
What can we do?

**Comment by DKbyo** [comment]
I already fixed this in https://github.com/willhlaw/node-firestore-backup-restore/pull/1 in the meantime you can pull my fork and install the fix, the instructions are in this gist https://gist.github.com/DKbyo/fe4a1b17ef6751286946c4b7e9116317

**Comment by chunggabriel** [comment]
Error Message for Restore
already exists. This means you called initializeApp() more than once with the same app name as the second argument. Make sure you provide a unique name every time you call initializeApp().

**Comment by chunggabriel** [comment]
Another question
Can we backup firestore first and then restore it later?
Any command is for restore only?

**Comment by willhlaw** [comment]
`npm install` error fixed in v1.1.2. Thanks @DKbyo for the PR in #1. 

@chunggabriel 'already exists' error means you are trying to backup and restore with the same credentials. The `project_id` in your two credentials json file need to be different so that when the firebase app initializes, it has two different appNames. 

@chunggabriel, will address restoring later from local backup in #3.
